### Get all words
GET http://127.0.0.1:8000/daily-dragon/vocabulary
Authorization: Bearer <token>

### Get random words
GET http://127.0.0.1:8000/daily-dragon/vocabulary?count=5
Authorization: Bearer <token>

###
OPTIONS http://127.0.0.1:8000/daily-dragon/vocabulary

### Add a new word
POST http://127.0.0.1:8000/daily-dragon/vocabulary
Authorization: Bearer <token>

{
    "word": "你好"
}

### Delete a word
# use tools/encode.py to encode Chinese characters
DELETE http://127.0.0.1:8000/daily-dragon/vocabulary/%E4%BD%A0%E5%A5%BD
Authorization: Bearer <token>
