### Get all words
GET https://c0ouez95i5.execute-api.us-west-2.amazonaws.com/daily-dragon/vocabulary
Authorization: Basic havryliuk <password>

### Get n random words
GET https://c0ouez95i5.execute-api.us-west-2.amazonaws.com/daily-dragon/vocabulary?count=5
Authorization: Basic havryliuk <password>

###
OPTIONS http://c0ouez95i5.execute-api.us-west-2.amazonaws.com/daily-dragon/vocabulary

### Add a new word
POST https://c0ouez95i5.execute-api.us-west-2.amazonaws.com/daily-dragon/vocabulary
Authorization: Basic havryliuk <password>

{
    "word": "你好"
}

### Delete a word
DELETE https://c0ouez95i5.execute-api.us-west-2.amazonaws.com/daily-dragon/vocabulary/%E4%BD%A0%E5%A5%BD
Authorization: Basic havryliuk <password>
